---  
- name: Deploy LNMP stack on CentOS 7  
  hosts: all  
  tasks:  
    
    - name: add nginx repo
      shell: rpm -ivh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
     
    - name: Install Nginx  
      yum:  
        name: nginx  
        state: present  
  
    - name: Start and enable Nginx  
      service:  
        name: nginx  
        state: started  
        enabled: yes  

    - name: Install MariaDB/MySQL  
      yum:  
        name: mariadb-server  
        state: present  
  
    - name: Start and enable MariaDB/MySQL  
      service:  
        name: mariadb  
        state: started  
        enabled: yes  
  
    - name: Secure MariaDB/MySQL installation  
      shell: |
       mysql_secure_installation <<EOF
        
        y
        123456
        123456



       EOF

    - name: copy
      copy:
       src: /root/lnmp/install.sql
       dest: /root/

    - name: Import SQL file  
      shell: mysql -uroot -p123456 < /root/install.sql
  
    - name: Install PHP and required extensions  
      yum:  
        name:  
          - php  
          - php-mysqlnd  
          - php-fpm  
        state: present
  
    - name: Start and enable PHP-FPM  
      service:  
        name: php-fpm  
        state: started  
        enabled: yes  
    
    - name: Configure Nginx to use PHP-FPM  
      template:  
        src: /root/lnmp/nginx.conf.j2  
        dest: /etc/nginx/nginx.conf  
        owner: root  
        group: root  
        mode: 0644  
      notify: restart nginx  
  
    

    - name: Copy PHP webpage  
      copy:  
        src: index.php  
        dest: /usr/share/nginx/html/index.php  
        owner: nginx  
        group: nginx  
        mode: 0644  
  
    - name: stop firewalld
      shell: systemctl stop firewalld
      
    - name: stop selinux
      shell: setenforce 0

  handlers:  
    - name: restart nginx  
      service:  
        name: nginx  
        state: restarted